begin;
select no_plan();
select tests.create_supabase_user('billing_owner', 'billing-owner@example.com');
select tests.create_supabase_user('billing_joiner', 'billing-joiner@example.com');
update auth.users set email_confirmed_at = now() where id = tests.get_supabase_uid('billing_owner');
create temporary table seat_billing_state (workspace_id uuid, invitation_id uuid, token text);
grant all on seat_billing_state to authenticated;
select tests.authenticate_as('billing_owner');
insert into seat_billing_state (workspace_id) select workspace_id from public.create_workspace('Billing team');
reset role;
select tests.enable_workspace_plan((select workspace_id from seat_billing_state), 'team', 1);
select is((select quantity from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state)), 1, 'Assigning a billing customer queues the existing membership count');
select ok(not has_table_privilege('authenticated', 'private.workspace_seat_billing_events', 'INSERT'), 'Clients cannot manufacture billing events');
select ok(not has_table_privilege('service_role', 'private.workspace_seat_billing_events', 'UPDATE'), 'Events are processed only by the billing database connection');
select tests.authenticate_as('billing_owner');
update seat_billing_state set (invitation_id, token) = (
  select invitation_id, invite_token from public.create_workspace_invitation((select workspace_id from seat_billing_state), 'billing-joiner@example.com')
);
select lives_ok($$ select * from public.create_workspace_invitation((select workspace_id from seat_billing_state), 'another@example.com') $$, 'Multiple pending invitations are permitted with one purchased seat');
reset role;
select is((select count(*) from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state)), 1::bigint, 'Invitations do not enqueue billable changes');
update auth.users set email_confirmed_at = now() where id = tests.get_supabase_uid('billing_joiner');
select tests.authenticate_as('billing_joiner');
select lives_ok($$ select * from public.accept_workspace_invitation((select invitation_id from seat_billing_state), (select token from seat_billing_state)) $$, 'Acceptance beyond purchased quantity succeeds');
reset role;
select results_eq($$ select quantity from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state) order by id $$, array[1,2], 'Acceptance records the new quantity after membership creation');
update public.workspace_memberships set role = 'admin' where workspace_id = (select workspace_id from seat_billing_state) and user_id = tests.get_supabase_uid('billing_joiner');
select is((select count(*) from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state)), 2::bigint, 'Role changes cannot cause billing');
update public.workspace_memberships set deleted_at = now() where workspace_id = (select workspace_id from seat_billing_state) and user_id = tests.get_supabase_uid('billing_joiner');
update public.workspace_memberships set deleted_at = null where workspace_id = (select workspace_id from seat_billing_state) and user_id = tests.get_supabase_uid('billing_joiner');
select results_eq($$ select quantity from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state) order by id $$, array[1,2,1,2], 'Removal and rejoining retain every transition in order');
update public.workspaces set seat_limit = 27 where id = (select workspace_id from seat_billing_state);
select is((select count(*) from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state)), 4::bigint, 'Stripe quantity webhooks do not create a feedback loop');
savepoint before_delete;
delete from public.workspace_memberships where workspace_id = (select workspace_id from seat_billing_state) and user_id = tests.get_supabase_uid('billing_joiner');
select is((select quantity from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state) order by id desc limit 1), 1, 'Hard removal also records the reduced quantity');
rollback to before_delete;
select is((select count(*) from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state)), 4::bigint, 'Membership rollback also rolls back its billing event');
update private.workspace_seat_billing_events set processed_at = now() where workspace_id = (select workspace_id from seat_billing_state);
update public.workspaces set seat_limit = 2 where id = (select workspace_id from seat_billing_state);
select is((select count(*) from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state) and processed_at is null), 0::bigint, 'Matching Stripe echoes create no new billing event');
update public.workspaces set seat_limit = 1 where id = (select workspace_id from seat_billing_state);
select is((select quantity from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state) and processed_at is null), 2, 'External quantity edits reconcile back to actual membership');
select tests.authenticate_as('billing_owner');
select lives_ok($$ select * from public.delete_workspace((select workspace_id from seat_billing_state)) $$, 'Owner can delete the paid workspace');
reset role;
select is((select quantity from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state) order by id desc limit 1), 0, 'Workspace deletion queues zero seats after previous membership events');
update public.workspace_memberships set deleted_at = now() where workspace_id = (select workspace_id from seat_billing_state) and user_id = tests.get_supabase_uid('billing_joiner');
select is((select quantity from private.workspace_seat_billing_events where workspace_id = (select workspace_id from seat_billing_state) order by id desc limit 1), 0, 'Cleanup of a deleted workspace cannot restore billed seats');
select * from finish();
rollback;
