// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async summaryLengthPolicy(request: SummaryLengthPolicyRequest) : Promise<Result<SummaryLengthPolicy | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|summary_length_policy", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dominantLanguage(request: DominantLanguageRequest) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|dominant_language", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareGeneratedSummary(request: PrepareGeneratedSummaryRequest) : Promise<Result<PreparedGeneratedSummary | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|prepare_generated_summary", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async composeGeneratedSummary(request: ComposeGeneratedSummaryRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|compose_generated_summary", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveGeneratedSummary(request: SaveGeneratedSummaryRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|save_generated_summary", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveGeneratedTitle(request: SaveGeneratedTitleRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|save_generated_title", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applySessionContentCorrections(request: SessionContentCorrectionsRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|apply_session_content_corrections", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async render(tpl: Template) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|render", { tpl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderCustom(templateContent: string, ctx: Partial<{ [key in string]: JsonValue }>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|render_custom", { templateContent, ctx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTemplateSource(template: EditableTemplate) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|get_template_source", { template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActivityCaptureSystem = { language: string | null }
export type ActivityCaptureUser = { appName: string; windowTitle: string | null; reason: string; fingerprint: string }
export type ChatSystem = { language: string | null }
export type ComposeGeneratedSummaryRequest = { text: string; title: string | null; tag_names: string[] }
export type ContextBlock = { contexts: SessionContext[]; currentSessionId: string | null }
export type DailySummaryAnalysis = { time: string; appName: string; windowTitle: string | null; reason: string; summary: string }
export type DailySummaryAppStat = { appName: string; count: number }
export type DailySummaryStats = { signalCount: number; screenshotCount: number; analysisCount: number; uniqueAppCount: number; firstSignal: string | null; lastSignal: string | null }
export type DailySummarySystem = { language: string | null }
export type DailySummaryUser = { date: string; timezone: string | null; stats: DailySummaryStats; topApps: DailySummaryAppStat[]; analyses: DailySummaryAnalysis[]; totalAnalysisCount: number; existingSummary: string | null }
export type DominantLanguageRequest = { texts: string[]; candidates: string[] }
export type EditableTemplate = "enhanceFormat" | "enhanceUser" | "titleUser"
export type EnhanceSystem = { language: string | null; formatOverride: string }
export type EnhanceTemplate = { title: string; description: string | null; sections: TemplateSection[] }
export type EnhanceUser = { session: Session; participants: Participant[]; template: EnhanceTemplate | null; transcripts: Transcript[]; preMeetingMemo: string; postMeetingMemo: string }
export type Event = { name: string }
export type EventContactCandidate = { name: string | null; email: string | null; isCurrentUser: boolean; isOrganizer: boolean }
export type EventContactSystem = Record<string, never>
export type EventContactUser = { title: string | null; description: string | null; candidates: EventContactCandidate[] }
export type Grammar = { task: "enhance"; sections: string[] | null } | { task: "title" } | { task: "tags" } | { task: "email-to-name" }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Participant = { name: string; jobTitle: string | null }
export type PendingAutoEnhanceGuard = { generation: string; expected_body: string; expected_body_format: string }
export type PrepareGeneratedSummaryRequest = { text: string; tag_sources: string[] }
export type PreparedGeneratedSummary = { text: string; tag_names: string[]; text_with_tags: string }
export type SaveGeneratedSummaryRequest = { session_id: string; owner_user_id: string; note_id: string; current_body: string; current_body_format: string; next_body: string; tag_names: string[]; pending_auto_enhance: PendingAutoEnhanceGuard | null }
export type SaveGeneratedTitleRequest = { session_id: string; current_title: string; next_title: string; documents: SessionDocumentUpdate[] }
export type Segment = { text: string; speaker: string }
export type Session = { title: string | null; startedAt: string | null; endedAt: string | null; event: Event | null }
export type SessionContentCorrectionsRequest = { session_id: string; summaries: SessionDocumentUpdate[]; transcripts: TranscriptCorrection[]; title: TitleCorrection | null }
export type SessionContext = { sessionId: string | null; title: string | null; date: string | null; rawContent: string | null; enhancedContent: string | null; meetingChat: string | null; transcript: Transcript | null; participants: Participant[]; event: Event | null }
export type SessionDocumentUpdate = { id: string; current_body: string; current_body_format: string; next_body: string }
export type SummaryLengthGuidance = { max_characters: number; min_sections: number; max_sections: number }
export type SummaryLengthMode = "crisp" | "balanced" | "detailed"
export type SummaryLengthPolicy = { mode: SummaryLengthMode; transcript_characters: number; guidance: SummaryLengthGuidance | null }
export type SummaryLengthPolicyRequest = { transcript_texts: string[]; mode: SummaryLengthMode; template_section_count: number }
export type Template = { activityCaptureSystem: ActivityCaptureSystem } | { activityCaptureUser: ActivityCaptureUser } | { dailySummarySystem: DailySummarySystem } | { dailySummaryUser: DailySummaryUser } | { enhanceSystem: EnhanceSystem } | { enhanceUser: EnhanceUser } | { eventContactSystem: EventContactSystem } | { eventContactUser: EventContactUser } | { titleSystem: TitleSystem } | { titleUser: TitleUser } | { chatSystem: ChatSystem } | { contextBlock: ContextBlock } | { toolSearchSessions: ToolSearchSessions } | { transcriptPatchSystem: TranscriptPatchSystem } | { transcriptPatchUser: TranscriptPatchUser }
export type TemplateSection = { title: string; description: string | null }
export type TitleCorrection = { current_title: string; next_title: string }
export type TitleSystem = { language: string | null }
export type TitleUser = { enhancedNote: string }
export type ToolSearchSessionItem = { id: string; title: string | null; excerpt: string | null; score: number; createdAt: number | null; sessionContext: SessionContext | null }
export type ToolSearchSessions = { query: string; results: ToolSearchSessionItem[] }
export type Transcript = { segments: Segment[]; startedAt: number | null; endedAt: number | null }
export type TranscriptCorrection = { id: string; current_words_json: string; current_memo: string; next_words_json: string; next_memo: string }
export type TranscriptPatchSystem = { language: string | null }
export type TranscriptPatchUser = { transcriptJson: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
